### PR TITLE
D-jsb updates

### PR DESCRIPTION
**Pull request by legoboyvdlp**
@FGMEMBERS @IAHM-COL @FGDATA
is this OK to merge?

### CODE REVIEW

**Comment by d-jsb** [comment]
What is this?

**Comment by ghost** [comment]
If FGMEMBERS wants to maintain a fork, by all means - maintain it. Active
CRJ700 development is maintained here by Henning and tightly coordinated
with FG devel mailing list and fgaddon.

2017-05-05 15:55 GMT+02:00 Henning <notifications@github.com>:

**Comment by d-jsb** [comment]
Please feel free to add any findings to the issue tracker (with or without patch file) but I will not merge anything from FGMEMBER. The last time I did it caused a major mess with license etc.

**Comment by legoboyvdlp** [comment]
I understand, and I apolgoize. This pull request was an accident; I was trying to do something else and just realized that this made a pull request FROM FGMEBMERS TO d-jsb, instead of vice-versa ;)

**Pull request closed without merging**
